#pragma once

// "Fake std"
#include "stdlib.h"

#include "include/assert.h"
#include "include/bitwise_utils.h"
#include "include/compiler_macros.h"
#include "include/cpp_support.h"
#include "include/debugger.h"
#include "include/deprecated.h"
#include "include/fake_keywords.h"
#include "include/macros.h"
#include "include/memory.h"
#include "include/numeric_types.h"
#include "include/os_macros.h"
#include "include/pointers.h"
#include "include/processor_macros.h"
#include "include/string.h"
#include "include/unsorted_yet.h"